name: Batch
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      test-sets: ${{ steps['define-test-sets'].outputs['test-sets'] }}
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - id: define-test-sets
        name: Define Test Sets
        run: node ./createTestSets.js
      - id: read-test-sets
        name: Read Test Sets
        run: echo "::set-output name=test-sets::$(cat ./prepareTestSets.json)"
        #
  test:
    runs-on: ubuntu-latest
    name: Test Batch (${{ fromJSON(matrix.chunk)['name'] }})
    needs:
      - setup
    strategy:
      matrix:
        chunk: ${{ fromJson(needs.setup.outputs['test-sets']) }}
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - name: jest
        run: echo ${{ matrix.chunk }} | jq '.tests | .[] | @text' | xargs npx jest
